// <auto-generated />
using System;
using MailRemoverAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MailRemoverAPI.Migrations
{
    [DbContext(typeof(MailRemoverDbContext))]
    [Migration("20221115205726_addedGmailMailboxes")]
    partial class addedGmailMailboxes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MailRemoverAPI.Entities.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f20266e0-d7bb-4d10-a231-7dc188d610bc"),
                            Address = "1234user@gmail.com",
                            Token = "b07f85be-45da",
                            Type = 0,
                            UserId = new Guid("b2001791-a6f6-4f83-ad57-c0aef67f22e8")
                        },
                        new
                        {
                            Id = new Guid("e9cde072-11f9-4de9-9e2c-0ef77136484d"),
                            Address = "1234wre2ruser@gmail.com",
                            Token = "a08885be-89da",
                            Type = 0,
                            UserId = new Guid("b2001791-a6f6-4f83-ad57-c0aef67f22e8")
                        },
                        new
                        {
                            Id = new Guid("aeaea436-a85d-40e7-83e9-2b26505abe32"),
                            Address = "rsdfe2ruser@gmail.com",
                            Token = "b07f96be-45da",
                            Type = 0,
                            UserId = new Guid("ba0e4f4d-913e-4406-a2bf-9ff49a6a9f58")
                        },
                        new
                        {
                            Id = new Guid("6c49fbbb-728d-476b-83c4-f4655930458e"),
                            Address = "lunasuo@gmail.com",
                            Token = "b07f45be-45da",
                            Type = 0,
                            UserId = new Guid("41fef1fb-17ed-4ec7-9cde-d51655ca5f15")
                        },
                        new
                        {
                            Id = new Guid("c7b770dc-5e86-4765-8426-31cd37282361"),
                            Address = "lapesuo@gmail.com",
                            Token = "b07f75be-45da",
                            Type = 0,
                            UserId = new Guid("f5d45886-1e2b-4547-bd09-e688bd266d84")
                        });
                });

            modelBuilder.Entity("MailRemoverAPI.Entities.Gmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Gmails");
                });

            modelBuilder.Entity("MailRemoverAPI.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2001791-a6f6-4f83-ad57-c0aef67f22e8"),
                            FirstName = "Tomas",
                            LastName = "Sinkevičius",
                            Password = "RjEUW1R58r"
                        },
                        new
                        {
                            Id = new Guid("ba0e4f4d-913e-4406-a2bf-9ff49a6a9f58"),
                            FirstName = "Greta",
                            LastName = "Virpšaitė",
                            Password = "@G3gng9t6XBe"
                        },
                        new
                        {
                            Id = new Guid("41fef1fb-17ed-4ec7-9cde-d51655ca5f15"),
                            FirstName = "Austėja",
                            LastName = "Naujokaitė",
                            Password = "3Gcoj6!Z1bnc"
                        },
                        new
                        {
                            Id = new Guid("f5d45886-1e2b-4547-bd09-e688bd266d84"),
                            FirstName = "Benas",
                            LastName = "Skripkiūnas",
                            Password = "*Y4!3l710POq"
                        });
                });

            modelBuilder.Entity("MailRemoverAPI.Entities.Email", b =>
                {
                    b.HasOne("MailRemoverAPI.Entities.User", "User")
                        .WithMany("Emails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MailRemoverAPI.Entities.Gmail", b =>
                {
                    b.HasOne("MailRemoverAPI.Entities.User", "User")
                        .WithMany("Gmails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MailRemoverAPI.Entities.User", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Gmails");
                });
#pragma warning restore 612, 618
        }
    }
}
