// <auto-generated />
using System;
using MailRemoverAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MailRemoverAPI.Migrations
{
    [DbContext(typeof(MailRemoverDbContext))]
    [Migration("20221121185554_AddedAddress")]
    partial class AddedAddress
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MailRemoverAPI.Entities.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4f6179c-0927-4897-b5b4-76dbab1ec412"),
                            Address = "1234user@gmail.com",
                            Token = "b07f85be-45da",
                            Type = 0,
                            UserId = new Guid("cd639164-cf49-4e73-b214-b4b8425beef6")
                        },
                        new
                        {
                            Id = new Guid("625188d2-57f5-4374-b3e9-68dcba810c48"),
                            Address = "1234wre2ruser@gmail.com",
                            Token = "a08885be-89da",
                            Type = 0,
                            UserId = new Guid("cd639164-cf49-4e73-b214-b4b8425beef6")
                        },
                        new
                        {
                            Id = new Guid("301d4077-c8ad-438b-b359-4b8664c0e595"),
                            Address = "rsdfe2ruser@gmail.com",
                            Token = "b07f96be-45da",
                            Type = 0,
                            UserId = new Guid("01dcd694-6240-49fd-87f7-0f01cb7cb423")
                        },
                        new
                        {
                            Id = new Guid("4cca919e-c789-4d41-ba91-571072600880"),
                            Address = "lunasuo@gmail.com",
                            Token = "b07f45be-45da",
                            Type = 0,
                            UserId = new Guid("27bc6aeb-ea79-4960-af78-351563d50d95")
                        },
                        new
                        {
                            Id = new Guid("1f9af880-a832-422b-b12d-96f5881637a9"),
                            Address = "lapesuo@gmail.com",
                            Token = "b07f75be-45da",
                            Type = 0,
                            UserId = new Guid("cd582234-5dad-4a43-81e4-8810a69b2bb8")
                        });
                });

            modelBuilder.Entity("MailRemoverAPI.Entities.Gmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Gmails");
                });

            modelBuilder.Entity("MailRemoverAPI.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd639164-cf49-4e73-b214-b4b8425beef6"),
                            FirstName = "Tomas",
                            LastName = "Sinkevičius",
                            Password = "RjEUW1R58r"
                        },
                        new
                        {
                            Id = new Guid("01dcd694-6240-49fd-87f7-0f01cb7cb423"),
                            FirstName = "Greta",
                            LastName = "Virpšaitė",
                            Password = "@G3gng9t6XBe"
                        },
                        new
                        {
                            Id = new Guid("27bc6aeb-ea79-4960-af78-351563d50d95"),
                            FirstName = "Austėja",
                            LastName = "Naujokaitė",
                            Password = "3Gcoj6!Z1bnc"
                        },
                        new
                        {
                            Id = new Guid("cd582234-5dad-4a43-81e4-8810a69b2bb8"),
                            FirstName = "Benas",
                            LastName = "Skripkiūnas",
                            Password = "*Y4!3l710POq"
                        });
                });

            modelBuilder.Entity("MailRemoverAPI.Entities.Email", b =>
                {
                    b.HasOne("MailRemoverAPI.Entities.User", "User")
                        .WithMany("Emails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MailRemoverAPI.Entities.Gmail", b =>
                {
                    b.HasOne("MailRemoverAPI.Entities.User", "User")
                        .WithMany("Gmails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MailRemoverAPI.Entities.User", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Gmails");
                });
#pragma warning restore 612, 618
        }
    }
}
